Configured Travis build to check the source distribution can be installed, closes #10

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -30,6 +30,14 @@ script:
     fi
   - cabal-1.18 check
   - cabal-1.18 sdist
+  - export SRC_TGZ=$(cabal-1.18 info . | awk '{print $2 ".tar.gz";exit}') ;
+    (cd dist/;
+    if [ -f "$SRC_TGZ" ]; then
+      cabal-1.18 install "$SRC_TGZ";
+    else
+      echo "expected '$SRC_TGZ' not found";
+      exit 1;
+    fi)
 
 after_script:
   - dist/build/hpc-coveralls/hpc-coveralls --display-report test-all
